import os

APP_PORT = 8080
APP_BASE_ADRESS = "http://localhost"
APP_HOST = "localhost"

SPOTIFY_API_BASE_ADRESS = "https://api.spotify.com/v1"
SPOTIFY_ACCOUNT_BASE_ADDRESS = "https://accounts.spotify.com"
SPOTIFY_CLIENT_ID = os.environ['SPOTIFY_CLIENT_ID']
SPOTIFY_CLIENT_SECRET = os.environ['SPOTIFY_CLIENT_SECRET']
SPOTIFY_CURRENT_USER_ADDRESS = "/me"
SPOTIFY_USERS_ADDRESS = "/users"
SPOTIFY_ACESS_TOKEN_ADDRESS = "/api/token"
SPOTIFY_PLAYLISTS_ADDRESS = "/playlists"
SPOTIFY_MY_PLAYLISTS_ADDRESS = SPOTIFY_CURRENT_USER_ADDRESS + SPOTIFY_PLAYLISTS_ADDRESS
SPOTIFY_SEARCH_ADDRESS = "/search"
REQUEST_USER_AUTH_SCOPE = "playlist-read-private playlist-modify-private playlist-modify-public"

ENVIRONMENT_ENV_VARIABLE = "ENVIRONMENT"
LOCAL_ENVIRONMENT = "LOCAL"
DEPLOY_ENVIRONMENT = "DEPLOY"

SPOTIFY_REFRESH_TOKEN_DB_KEY = "SpotifyAPIRefreshToken"
ARCHIVE_PLAYLIST_ID_DB_KEY = "ArchivePlaylistId"
SPOTIFY_USER_ID_DB_KEY = "UserSpotifyId"


def SPOTIFY_USER_PLAYLISTS_ADDRESS(
    user_id): return SPOTIFY_API_BASE_ADRESS + SPOTIFY_USERS_ADDRESS + "/" + user_id + SPOTIFY_PLAYLISTS_ADDRESS


def SPOTIFY_PLAYLISTS_TRACKS_ADDRESS(
    playlist_id): return SPOTIFY_API_BASE_ADRESS + SPOTIFY_PLAYLISTS_ADDRESS + "/" + playlist_id + "/tracks"
